debug: false
random_seed: -1
embed_style: same
gpu: 0
max_steps: 100000
project_name: lili-grok
batchsize: 0
n_layers: 4
n_heads: 4
d_model: 256
dropout: 0.0
weight_noise: 0.0
non_linearity: relu
max_context_len: 100
math_operator: pfactor
operand_length: 1
train_data_pct: 50
warmup_steps: 10
group: c4
anneal_lr_steps: 100000
forward_mode: false
forward_forward_mode: true
reverse_mode: false
anneal_lr: false
max_lr: 0.001
weight_decay: 1.0
weight_decay_kind: to_zero
noise_factor: 0
save_activations: false
save_outputs: false
logdir: logs
datadir: data
d_key: -1
checkpoint_path: None
mode: ff
