defaults:
  - _self_  # Override values within this file with values in selected files.
  - exp: ff
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
debug: False
random_seed: 42
embed_style: same
gpu: 0
max_steps: 100000 # 000
project_name: grok_m
batchsize: 0
n_layers: 2
n_heads: 4
d_model: 128
dropout: 0.0
cyclic_consistency: False
do_tta: False
weight_noise: 0.0
non_linearity: "relu"
max_context_len: 50
math_operator: "+"
val_batchify: False
f_coef: 1.0
multi_task: False
math_operator_2: "-"
multi_coef: 1.0
tta_coef: 1.0
inv_coef: 1.0
cc_coef: 1.0


operand_length: 1
train_data_pct: 80
warmup_steps: 10
group: none
anneal_lr_steps: 100000
forward_mode: False
forward_forward_mode: False
reverse_mode: False
anneal_lr: False
max_lr: 1e-3
weight_decay: 0
weight_decay_kind: to_zero
noise_factor: 0
save_activations: False
save_outputs: False
logdir: logs
datadir: data
d_key: -1
checkpoint_path: None
data_list_len: 7
k: 3



hydra:
  output_subdir: /home/mprabhud/phd_projects/grok/exps
  run:
    dir: /home/mprabhud/phd_projects/grok/exps
  sweep:
    dir: /home/mprabhud/phd_projects/grok/exps
    subdir: /home/mprabhud/phd_projects/grok/exps