defaults:
  - _self_  # Override values within this file with values in selected files.
  - exp: f
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
debug: False
random_seed: -1
embed_style: same
gpu: 0
max_steps: 100000 # 000
project_name: sid-grok
batchsize: 0
n_layers: 2
n_heads: 4
d_model: 128
dropout: 0.2
weight_noise: 0.0
non_linearity: "relu"
max_context_len: 50
math_operator: "+"
operand_length: 1
train_data_pct: 80
warmup_steps: 10
group: none
anneal_lr_steps: 100000
forward_mode: False
forward_forward_mode: False
reverse_mode: False
anneal_lr: True
max_lr: 1e-3
weight_decay: 0.1
weight_decay_kind: to_zero
noise_factor: 0
save_activations: False
save_outputs: False
logdir: logs
datadir: data
d_key: -1
checkpoint_path: None
use_original_tokenizer: True
use_regression: False
data_list_len: 5
k: 3

hydra:
  output_subdir: /home/mprabhud/sp/grok
  run:
    dir: /home/mprabhud/sp/grok
  sweep:
    dir: /home/mprabhud/sp/grok
    subdir: /home/mprabhud/sp/grok
